# Generated by Django 2.2.5 on 2019-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sypnopsis',
            new_name='synopsis',
        ),
        migrations.AddField(
            model_name='event',
            name='recommendation_index',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='recommendation_index',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
