# Generated by Django 2.2.5 on 2019-09-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190920_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercluster',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OLifer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('answers', models.ManyToManyField(to='app.Answer')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UserCluster')),
                ('saved_events', models.ManyToManyField(to='app.Event')),
                ('saved_movies', models.ManyToManyField(to='app.Movie')),
            ],
        ),
    ]
