# Generated by Django 2.2.5 on 2019-09-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190920_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OLifer'),
        ),
    ]
