# Generated by Django 2.2.5 on 2019-09-20 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showing_until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
