# Generated by Django 2.2.5 on 2019-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190920_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olifer',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='app.Answer'),
        ),
        migrations.AlterField(
            model_name='olifer',
            name='saved_events',
            field=models.ManyToManyField(blank=True, null=True, to='app.Event'),
        ),
        migrations.AlterField(
            model_name='olifer',
            name='saved_movies',
            field=models.ManyToManyField(blank=True, null=True, to='app.Movie'),
        ),
    ]
